### ISSUE TITLE
Requesting to add alphanumeric and special character '_' Identifiers

### ISSUE THREAD

**Issue by sivasai-133** [myCSEprojects/Zebra#59]
```
>> int under_score = 13;
Traceback (most recent call last):
  File "/home/sivasai_133/Documents/sem6/compilers/project/zebra.py", line 123, in <module>
    interactiveShell()
  File "/home/sivasai_133/Documents/sem6/compilers/project/zebra.py", line 97, in interactiveShell
    output = execute(lines, resolverScopes, typecheckerScopes, scopes)
  File "/home/sivasai_133/Documents/sem6/compilers/project/zebra.py", line 56, in execute
    raise e
  File "/home/sivasai_133/Documents/sem6/compilers/project/zebra.py", line 37, in execute
    programAST = parse(stream) 
  File "/home/sivasai_133/Documents/sem6/compilers/project/parser.py", line 712, in parse
    programAST = Parser.parse_program (
  File "/home/sivasai_133/Documents/sem6/compilers/project/parser.py", line 697, in parse_program
    seqs.append(self.parse_declare())
  File "/home/sivasai_133/Documents/sem6/compilers/project/parser.py", line 690, in parse_declare
    return self.parse_vardec()
  File "/home/sivasai_133/Documents/sem6/compilers/project/parser.py", line 547, in parse_vardec
    if(self.lexer.peek_token().val != "="):
  File "/home/sivasai_133/Documents/sem6/compilers/project/lexer.py", line 234, in peek_token
    self.save = self.next_token()
  File "/home/sivasai_133/Documents/sem6/compilers/project/lexer.py", line 224, in next_token
    raise Exception("Invalid literal")
Exception: Invalid literal
```

```
>> boolean a1 = false;
TokenError(line:0): Expected a ';'
```

**Comment by RajeshVoorugonda** [comment]
Issue resolved.

**Comment by myCSEprojects** [comment]
Issue got resolved
